language: node_js
node_js:
  - "5.4"
before_script:
  - npm install -g gulp
script: gulp
env:
  global:
    - "FTP_USER=admin@experiente-gastronomice.ro"
    - "FTP_PASSWORD=9970723929"
after_success:
  # - "curl --ftp-create-dirs -T ./build/index.html -u $FTP_USER:$FTP_PASSWORD ftp://u83224274.1and1-data.host/index.html"
  - find ./build/ -type f -exec curl -v --ftp-create-dirs --ftp-ssl -T "{}" -u $FTP_USER:$FTP_PASSWORD ftp://u83224274.1and1-data.host/"{}" \;